insert into librarie(adresa, telefon, email) values('Aleea Decebal nr 9', '0757772576', 'librarie@yahoo.com');

insert into angajat(librarie_id, nume_angajat) values(100, 'Ana Maria');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6010728270016', '1 Mai', '0754675891', 'anamaria@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100, 'Maria Ioana');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6910812270016', 'Aleea Decebal', '0768594632', 'maria@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100, 'Alexandru Ion');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6001123270016', 'Bulevardul Decebal', '0712345678', 'alexandru@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100, 'Marian Mihai');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6020330270016', 'Bulevardul Stefan', '0765473829', 'marian@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100, 'Diana Elena');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6010527270016', 'Bulevardul Chimiei', '0785947352', 'diana@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100, 'Ioana Pascaru');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6000327270016', 'Strada Garii', '0765473645', 'ioana@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100, 'Bianca Creanga');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6020513270016', 'Aleea Decebal', '0765748392', 'biancac@yahoo.com'); 
insert into angajat(librarie_id, nume_angajat) values(100, 'Bogdan Alexandru');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6020510270016', 'Strada Petrodava', '0745628965', 'bogdan@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100, 'Amalaia Creanga');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6000630270016', 'Strada Franceza', '0754691234', 'amalia@yahoo.com');
insert into angajat(librarie_id, nume_angajat) values(100,  'Ionut Vasile');
insert into detalii_angajat values(angajat_angajat_id_seq.CURRVAL, '6000103270016', 'Bulevardul Decebal', '0754019287', 'inout@yahoo.com');

insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Mihai Florin', '6010730270016', 1234567890123456, '0718293456', 'Aleea Decebal', 1);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Ana Mihaela', '6960829270016', 6578490123456923, '0794756382', 'Soseaua Nationala', 0);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Mihai Constantin', '6980506270016', 7685903764536728, '0745678904', 'Strada Garii', 1);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Andreea Bianca', '6990517270016', 7685940375647382, '0786950465', 'Bulevardul Decebal', 0);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Andrei Bogdan', '6030829270016', 5768594089376582, '0735467283', 'Starada Garii', 1);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Amalia Ioana', '6010330270016', 5463728907685946, '0745362786', '1 Mai', 0);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Ioana Bianca', '6020112270016', 6574890243517869, '0754638901', '1 Mai', 1);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Carmen Pascaru', '6000205270016', 8903425674891023, '0724536748', 'Strada Garii', 1);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Diana Ioana', '6980110270016', 7485901234567182, '0712345678', 'Aleea Decebal', 0);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Bianca Elena', '6971026270016', 1526574890145678, '0712859403', 'Aleea Decebal', 1);
insert into client(nume_client, cnp_client, nr_card, telefon, adresa, card_fidelitate) values('Ionut Constantin', '6030120270016', 6574910234657890, '0712378654', 'Strada Garii', 0);

insert into furnizori(nume_furnizor, adresa, email) values('Pelikan', 'Strada Covaci', 'pelikan@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Bic', 'Strada Ilfov', 'bic@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Daco', 'Strada Doamnei', 'daco@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Herlitx', 'Strada Franceza', 'herlitx@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Schneider', 'Centrul Vechi', 'schneider@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Castell', 'Starada Garii', 'castell@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Centropen', 'Bulevardul Decebal', 'centro@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Crayola', 'Bld Gral Dascalescu', 'crayola@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Niculescu', 'Aleea Decebal', 'niculescu@yahoo.com');
insert into furnizori(nume_furnizor, adresa, email) values('Aramis', 'Strada Ilfov', 'aramis@yahoo.com');

insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id)  values('Caiet A4', 5.4 , 20, 120);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id)  values('Stilou', 20, 30, 130);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id)  values('Pix', 2.3, 10, 110);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id)  values('Manual', 15.6, 10, 190);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id)  values('Pasta corectoare', 2.4, 12, 100);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id)  values('Acuarele', 7.8, 9, 140);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id)  values('XEROX', 0.50, 0, 120);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id) values('Marker', 2.5, 40, 150);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id) values('Culegere', 18.67, 30, 180);
insert into produse(nume_produs, pret, cantitate_disponibila, furnizor_id) values('Bloc de desen', 9.50, 28, 190);

insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('18.12.2021', 'dd-mm-yyyy'), 20, 10, (select nr_card from client where client_id=10));  
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata) values(100, vanzare_nr_bon_seq.CURRVAL, 2);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('17.10.2021', 'dd-mm-yyyy'), 21, 11, (select nr_card from client where client_id=11));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata) values(100, vanzare_nr_bon_seq.CURRVAL, 12);
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(160, vanzare_nr_bon_seq.CURRVAL, 3);
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(175, vanzare_nr_bon_seq.CURRVAL, 1);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('01.06.2020', 'dd-mm-yyyy'), 22, 13, (select nr_card from client where client_id=13));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(115, vanzare_nr_bon_seq.CURRVAL, 2);
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(190, vanzare_nr_bon_seq.CURRVAL, 1);
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(130, vanzare_nr_bon_seq.CURRVAL, 2);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('15.10.2021', 'dd-mm-yyyy'), 20, 14, (select nr_card from client where client_id=14));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(190, vanzare_nr_bon_seq.CURRVAL, 14);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('01.06.2021', 'dd-mm-yyyy'), 21, 12, (select nr_card from client where client_id=12));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(145, vanzare_nr_bon_seq.CURRVAL, 1);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('10.01.2021', 'dd-mm-yyyy'), 24, 19, (select nr_card from client where client_id=19));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(235, vanzare_nr_bon_seq.CURRVAL, 1);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('29.05.2021', 'dd-mm-yyyy'), 25, 16, (select nr_card from client where client_id=16));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(205, vanzare_nr_bon_seq.CURRVAL, 4);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('01.12.2021', 'dd-mm-yyyy'), 29, 18, (select nr_card from client where client_id=18));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(160, vanzare_nr_bon_seq.CURRVAL, 3);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('01.06.2021', 'dd-mm-yyyy'), 28, 17, (select nr_card from client where client_id=17));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(220, vanzare_nr_bon_seq.CURRVAL, 2);
insert into vanzare(data, angajat_id, client_id, nr_card) values(to_date('01.06.2021', 'dd-mm-yyyy'), 27, 15, (select nr_card from client where client_id=15));
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(190, vanzare_nr_bon_seq.CURRVAL, 14);
insert into detalii_vanzare(produse_produs_id, vanzare_nr_bon, cantitate_cumparata)  values(235, vanzare_nr_bon_seq.CURRVAL, 1);

select * from librarie;
select * from angajat;
select * from detalii_angajat;
select * from client;
select * from furnizori;
select * from produse;
select * from vanzare;
select * from detalii_vanzare;
